version: '3.8'

services:
  # React フロントエンド
  frontend:
    build:
      context: ./frontend
      target: builder
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite  # Viteキャッシュディレクトリを除外
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_HMR_PORT=3000
      - VITE_FORCE_POLLING=true  # 追加の強制ポーリング
    networks:
      - app-network
    restart: unless-stopped

  # Flask バックエンド
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # nginx リバースプロキシ
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge