version: '3.8'

services:
  # React フロントエンド
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite  # Viteキャッシュディレクトリを除外
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_HMR_PORT=3000
      - VITE_FORCE_POLLING=true  # 追加の強制ポーリング
    networks:
      - app-network

  # Flask バックエンド
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  # nginx リバースプロキシ
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge